name: 🧩 Auto-generate GitHub Profile README

on:
  schedule:
    - cron: '0 6 * * *' # Runs daily at 6:00 AM UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Clone Repository
        uses: actions/checkout@v3

      - name: 🧠 Generate README.md from template
        uses: jaywcjlove/github-profile-generator@main
        with:
          config: .github/profile-template.yml

      - name: 🚀 Commit and Push if changed
        uses: EndBug/add-and-commit@v9
        with:
          message: "📝 Update profile README"
          add: "README.md"
